FROM golang:1.24-alpine AS builder

WORKDIR /src
COPY shared/go.mod shared/go.sum* /src/shared/
COPY api/go.mod api/go.sum* /src/api/
COPY shared/ /src/shared/

WORKDIR /src/api
RUN go mod download

COPY api/ /src/api/
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o /src/api/api main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /src/api/api .

EXPOSE 9000

ENTRYPOINT ["/app/api"]
