apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-headless-svc
  namespace: metrics-server-ns
  labels:
    app: metrics-collector
spec:
  clusterIP: None
  selector:
    app: metrics-collector
  ports:
  - name: http
    port: 9000
    targetPort: http
    protocol: TCP
