apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-collector-daemonset
  namespace: metrics-server-ns
  labels:
    app: metrics-collector
spec:
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      hostPID: true
      containers:
      - name: metrics-collector-container
        image: ghcr.io/ilcm96/dku-ce-k8s-metrics-server/collector:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: true
        volumeMounts:
        - name: procfs
          mountPath: /proc
          readOnly: true
        - name: cgroupfs
          mountPath: /sys/fs/cgroup
          readOnly: true
      volumes:
      - name: procfs
        hostPath:
          path: /proc
          type: Directory
      - name: cgroupfs
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
