name: Build and Push API Image

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'Dockerfile.api'
      - '.github/workflows/build-push-api.yaml'

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}

      - name: Build and push API Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ghcr.io/ilcm96/dku-ce-k8s-metrics-server/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
