name: Build and Push Collector Image

on:
  push:
    branches:
      - main
    paths:
      - 'collector/**'
      - 'Dockerfile.collector'
      - '.github/workflows/build-push-collector.yml'

jobs:
  build-and-push-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Collector Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.collector
          push: true
          tags: ghcr.io/ilcm96/dku-ce-k8s-metrics-server/collector:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
